Add support for Control4 Rooms
lawtancool/pyControl4 pull request #20
Opened 2022-04-26 00:11 UTC by kdkavanagh

2022-09-09 13:13 UTC, nalin29 commented
Is their a reason this pull request hasn't been merged? Is the project stalled? It seems that room integration is big feature for media control and I would like to contribute to home assistant by including room control using pycontrol4 assuming the request is merged.

2022-09-10 03:56 UTC, nalin29 commented
Additionally, I have noticed that this is not integrated with the websocket implementation it seems that the websocket cannot subscribe to room updates. Is there a way I can test and get my own websocket working through trial and error. What were the steps taken to capture api and websocket messages?

2022-09-10 16:09 UTC, kdkavanagh commented
The websocket API seemed to require some unique handshake process to fully connect.  Beyond that, the two methods seemed functionally similar and I didnt need any time-sensitive push updates into HA.  It was a bit easier to just use the REST API, especially since the rest of this library was using that as well.  

To reverse engineer the API, I had to MITM the android app installed on an old android phone I had lying around - I needed to rebuild the apk with custom CA certs and use BurpSuite Community edition to intercept the API calls from the app.  Unfortunately I dont recall the exact set of steps, I just remember it was a bit of a pain, but there are tutorials out there since this is a pretty common need for app developers

2022-09-10 16:11 UTC, kdkavanagh commented
+1 re: the merge question.  In the meantime, I've been using a local install of this plugin+the HA integration I wrote.  I can probably get those HA changes cleaned up and PR'd if that'd be helpful

2022-09-10 17:43 UTC, nalin29 commented
Thank you. Yeah I installed your library and was able to change to current HA plugin to support my media rooms for source and volume/power control using the current polling approach. It would be better to be push and not as hard coded.

2023-02-06 16:17 UTC, nalin29 commented
I noticed that you have forked the home assistant core and modified the control4 integration there. What features have you got working since I have a version that I made a while back but is pretty bare bones and diy. If you need someone to help test it let me know.

2023-02-10 17:55 UTC, lawtancool requested changes

2023-02-10 17:55 UTC, lawtancool commented on pyControl4/room.py
> +        await self.setSource(source_id, audio_only=False)
Since we have two different set audio/set audio and video methods, the `setSource` method should be private (`_setSource`)?

2023-02-15 03:34 UTC, lawtancool commented
Closed by #21

2023-02-15 03:34 UTC, closed without merging